name = "cookup"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "cookup"
database_id = "0fed06da-838b-4b9c-b60e-e7eea0eab7c8"
migrations_dir = "migrations"

[observability]
enabled = false
